/** HTML svg elements */
export const EL_SVG = {
    A: { val: "a" }, // Yep, its actually an SVG
    ANIMATE: { val: "animate" },
    ANIMATEMOTION: { val: "animateMotion" },
    ANIMATETRANSFORM: { val: "animateTransform" },
    CIRCLE: { val: "circle" },
    CLIPPATH: { val: "clipPath" },
    DEFS: { val: "defs" },
    DESC: { val: "desc" },
    ELLIPSE: { val: "ellipse" },
    FEBLEND: { val: "feBlend" },
    FECOLORMATRIX: { val: "feColorMatrix" },
    FECOMPONENTTRANSFER: { val: "feComponentTransfer" },
    FECOMPOSITE: { val: "feComposite" },
    FECONVOLVEMATRIX: { val: "feConvolveMatrix" },
    FEDIFFUSELIGHTING: { val: "feDiffuseLighting" },
    FEDISPLACEMENTMAP: { val: "feDisplacementMap" },
    FEDISTANTLIGHT: { val: "feDistantLight" },
    FEDROPSHADOW: { val: "feDropShadow" },
    FEFLOOD: { val: "feFlood" },
    FEFUNCA: { val: "feFuncA" },
    FEFUNCB: { val: "feFuncB" },
    FEFUNCG: { val: "feFuncG" },
    FEFUNCR: { val: "feFuncR" },
    FEGAUSSIANBLUR: { val: "feGaussianBlur" },
    FEIMAGE: { val: "feImage" },
    FEMERGE: { val: "feMerge" },
    FEMERGENODE: { val: "feMergeNode" },
    FEMORPHOLOGY: { val: "feMorphology" },
    FEOFFSET: { val: "feOffset" },
    FEPOINTLIGHT: { val: "fePointLight" },
    FESPECULARLIGHTING: { val: "feSpecularLighting" },
    FESPOTLIGHT: { val: "feSpotLight" },
    FETILE: { val: "feTile" },
    FETURBULENCE: { val: "feTurbulence" },
    FILTER: { val: "filter" },
    FOREIGNOBJECT: { val: "foreignObject" },
    G: { val: "g" },
    IMAGE: { val: "image" },
    LINE: { val: "line" },
    LINEARGRADIENT: { val: "linearGradient" },
    MARKER: { val: "marker" },
    MASK: { val: "mask" },
    METADATA: { val: "metadata" },
    MPATH: { val: "mpath" },
    PATH: { val: "path" },
    PATTERN: { val: "pattern" },
    POLYGON: { val: "polygon" },
    POLYLINE: { val: "polyline" },
    RADIALGRADIENT: { val: "radialGradient" },
    RECT: { val: "rect" },
    SCRIPT: { val: "script" },
    SET: { val: "set" },
    STOP: { val: "stop" },
    STYLE: { val: "style" },
    /**
     * For larger svg-based components with lots of moving parts, 
     * consider {@link SvgContext}, or creating something on your end that is similar.
     */
    SVG: { val: "svg" },
    SWITCH: { val: "switch" },
    SYMBOL: { val: "symbol" },
    TEXT: { val: "text" },
    TEXTPATH: { val: "textPath" },
    TITLE: { val: "title" },
    TSPAN: { val: "tspan" },
    USE: { val: "use" },
    VIEW: { val: "view" },
} as const;

