import { getNormalizedKey } from "./im-dom";

/** Keyboard keys */
export const KEY = {
    // 1 to 9,0 - main numbers
    A1: getNormalizedKey("1"),
    A2: getNormalizedKey("2"),
    A3: getNormalizedKey("3"),
    A4: getNormalizedKey("4"),
    A5: getNormalizedKey("5"),
    A6: getNormalizedKey("6"),
    A7: getNormalizedKey("7"),
    A8: getNormalizedKey("8"),
    A9: getNormalizedKey("9"),
    A0: getNormalizedKey("0"),
    MINUS: getNormalizedKey("-"),
    EQUALS: getNormalizedKey("="),

    Q: getNormalizedKey("Q"),
    W: getNormalizedKey("W"),
    E: getNormalizedKey("E"),
    R: getNormalizedKey("R"),
    T: getNormalizedKey("T"),
    Y: getNormalizedKey("Y"),
    U: getNormalizedKey("U"),
    I: getNormalizedKey("I"),
    O: getNormalizedKey("O"),
    P: getNormalizedKey("P"),
    OPEN_BRACKET: getNormalizedKey("["),
    CLOSE_BRACKET: getNormalizedKey("]"),
    BACKSLASH: getNormalizedKey("\\"),

    A: getNormalizedKey("A"),
    S: getNormalizedKey("S"),
    D: getNormalizedKey("D"),
    F: getNormalizedKey("F"),
    G: getNormalizedKey("G"),
    H: getNormalizedKey("H"),
    J: getNormalizedKey("J"),
    K: getNormalizedKey("K"),
    L: getNormalizedKey("L"),
    SEMICOLON: getNormalizedKey(","),
    QUOTE: getNormalizedKey("'"),
    ENTER: getNormalizedKey("Enter"),

    Z: getNormalizedKey("Z"),
    X: getNormalizedKey("X"),
    C: getNormalizedKey("C"),
    V: getNormalizedKey("V"),
    B: getNormalizedKey("B"),
    N: getNormalizedKey("N"),
    M: getNormalizedKey("M"),
    COMMA: getNormalizedKey(","),
    PERIOD: getNormalizedKey("."),
    FORWAR_SLASH: getNormalizedKey("/"),

    SHIFT: getNormalizedKey("Shift"),
    CTRL: getNormalizedKey("Control"),
    META: getNormalizedKey("Meta"),
    ALT: getNormalizedKey("Alt"),
    MOD: getNormalizedKey("Modifier"), // Either CTRL or META

    SPACE: getNormalizedKey(" "),
    BACKSPACE: getNormalizedKey("Backspace"),
    ARROW_UP: getNormalizedKey("ArrowUp"),
    ARROW_DOWN: getNormalizedKey("ArrowDown"),
    ARROW_LEFT: getNormalizedKey("ArrowLeft"),
    ARROW_RIGHT: getNormalizedKey("ArrowRight"),
} as const;
